### ISSUE TITLE
Translation files in this repository do not reflect the real FA releases

### ISSUE THREAD

**Issue by pigletto** [FusionAuth/fusionauth-localization#48]
I've installed FA 1.32.1 and in the translations, there are some strings like device-link-count-exceeded-next-step that are not present in messages.properties in this repository (neither in master nor in 1.32.1 tag). I think I've also seen a similar issues with older releases.

**Comment by mooreds** [comment]
Thanks for the feedback @pigletto .

I've confirmed this is true. I can take care of this this time, but will see if we can automate this to avoid the issue in the future.

**Comment by mooreds** [comment]
With the rollout of the fix for https://github.com/FusionAuth/fusionauth-issues/issues/1563 we now should always see the latest version of the messages file in this repo.

I'm going to close this out, but thanks for reporting, @pigletto ! 

If I misunderstood your goals/intent for this issue, please feel free to re-open.
